// <auto-generated />
using System;
using CustodyChain.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustodyChain.Web.Migrations
{
    [DbContext(typeof(CustodyChainDbContext))]
    [Migration("20260923073739_ModeloCompleto16Entidades")]
    partial class ModeloCompleto16Entidades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Anexo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Algoritmo")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("CaminhoRelativo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("EnviadoPorId")
                        .HasColumnType("bigint");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("VestigioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EnviadoPorId");

                    b.HasIndex("HashSha256");

                    b.HasIndex("VestigioId");

                    b.ToTable("ANEXO", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Armazenamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Central")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("EntradaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Posicao")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateOnly?>("PrazoGuardaAte")
                        .HasColumnType("date");

                    b.Property<long?>("RecebidoPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SaidaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("VestigioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RecebidoPorId");

                    b.HasIndex("VestigioId");

                    b.ToTable("ARMAZENAMENTO", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Credencial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EmissorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EmitidaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<long?>("ProcessoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<long>("TitularId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ValidaAte")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("VestigioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmissorId");

                    b.HasIndex("Identificador")
                        .IsUnique();

                    b.HasIndex("ProcessoId");

                    b.HasIndex("TitularId");

                    b.HasIndex("VestigioId");

                    b.ToTable("CREDENCIAL", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Descarte", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AprovadoPorId")
                        .HasColumnType("bigint");

                    b.Property<long>("AutorizacaoAnexoId")
                        .HasColumnType("bigint");

                    b.Property<string>("DidMagistrado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ExecutadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<long?>("SolicitadoPorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("VestigioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AprovadoPorId");

                    b.HasIndex("AutorizacaoAnexoId");

                    b.HasIndex("SolicitadoPorId");

                    b.HasIndex("VestigioId");

                    b.ToTable("DESCARTE", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Interveniente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AtivadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Did")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DidEmissor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Lotacao")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Matricula")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Orgao")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<byte>("PerfilId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Did")
                        .IsUnique();

                    b.HasIndex("PerfilId");

                    b.ToTable("INTERVENIENTE", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Lacre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AplicadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("AplicadoPorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FotoAnexoId")
                        .HasColumnType("bigint");

                    b.Property<string>("JustificativaRompimento")
                        .HasColumnType("text");

                    b.Property<long?>("LacreAnteriorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime?>("RompidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("RompidoPorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("VestigioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AplicadoPorId");

                    b.HasIndex("FotoAnexoId");

                    b.HasIndex("LacreAnteriorId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("RompidoPorId");

                    b.HasIndex("VestigioId");

                    b.ToTable("LACRE", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Laudo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AnexoPdfId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("AssinadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("AssinadoPorId")
                        .HasColumnType("bigint");

                    b.Property<string>("AssinaturaEd25519")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Conteudo")
                        .HasColumnType("longtext");

                    b.Property<string>("HashLaudo")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<string>("HashVestigios")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<long?>("LaudoAnteriorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<long>("PericiaId")
                        .HasColumnType("bigint");

                    b.Property<short>("Versao")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("AnexoPdfId");

                    b.HasIndex("AssinadoPorId");

                    b.HasIndex("LaudoAnteriorId");

                    b.HasIndex("PericiaId");

                    b.HasIndex("Numero", "Versao")
                        .IsUnique();

                    b.ToTable("LAUDO", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.LogAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("HashAnterior")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<string>("HashRegistro")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<long?>("IntervenienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<long?>("RegistroId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("HashRegistro")
                        .IsUnique();

                    b.HasIndex("IntervenienteId");

                    b.ToTable("LOG_AUDITORIA", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Movimentacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AprovadoPorId")
                        .HasColumnType("bigint");

                    b.Property<string>("CodigoRastreamento")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<bool?>("CondicoesAdequadas")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("CriadoPorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataHoraChegada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataHoraSaida")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoIntercorrencia")
                        .HasColumnType("text");

                    b.Property<long?>("DestinoId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Etapa")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool?>("HouveIntercorrencia")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MotivoRecusa")
                        .HasColumnType("text");

                    b.Property<long?>("OrigemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("VestigioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AprovadoPorId");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("DestinoId");

                    b.HasIndex("OrigemId");

                    b.HasIndex("VestigioId");

                    b.ToTable("MOVIMENTACAO", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.OperacaoAmostra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExecutadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ExecutadoPorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PericiaId")
                        .HasColumnType("bigint");

                    b.Property<string>("QuantidadeDescrita")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("VestigioOrigemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VestigioResultanteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExecutadoPorId");

                    b.HasIndex("PericiaId");

                    b.HasIndex("VestigioOrigemId");

                    b.HasIndex("VestigioResultanteId");

                    b.ToTable("OPERACAO_AMOSTRA", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Perfil", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MetodoDid")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("PERFIL", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Pericia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaPericial")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CredencialId")
                        .HasColumnType("bigint");

                    b.Property<string>("MotivoRecusa")
                        .HasColumnType("text");

                    b.Property<long?>("PeritoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<long>("ProcessoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RecebidaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("SolicitadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("VestigioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CredencialId");

                    b.HasIndex("PeritoId");

                    b.HasIndex("ProcessoId");

                    b.HasIndex("VestigioId");

                    b.ToTable("PERICIA", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Processo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("DataAbertura")
                        .HasColumnType("date");

                    b.Property<string>("NomeOperacao")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("OrgaoOrigem")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("PROCESSO", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.RegistroLedger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AncoradoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("Bloco")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EntidadeOrigem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Erro")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("json");

                    b.Property<long>("RegistroOrigemId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Tentativas")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("TxHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long?>("VestigioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VestigioId");

                    b.HasIndex("Estado", "CriadoEm");

                    b.HasIndex("EntidadeOrigem", "RegistroOrigemId", "Evento")
                        .IsUnique();

                    b.ToTable("REGISTRO_LEDGER", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.TipoVestigio", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("AreaPericial")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("ExigeHash")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("TIPO_VESTIGIO", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Vestigio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CriadorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustodianteAtualId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataHoraColeta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescricaoIntercorrencia")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<byte>("EtapaAtual")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("FaseAtual")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool?>("HouveIntercorrencia")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LocalColeta")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MetodoColeta")
                        .HasColumnType("text");

                    b.Property<string>("NumeroEvidencia")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<long>("ProcessoId")
                        .HasColumnType("bigint");

                    b.Property<string>("RotuloConjunto")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("RotuloEvidencia")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<short>("TipoVestigioId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.HasIndex("CustodianteAtualId");

                    b.HasIndex("ProcessoId");

                    b.HasIndex("RotuloConjunto");

                    b.HasIndex("RotuloEvidencia")
                        .IsUnique();

                    b.HasIndex("TipoVestigioId");

                    b.ToTable("VESTIGIO", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Anexo", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "EnviadoPor")
                        .WithMany()
                        .HasForeignKey("EnviadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Vestigio", "Vestigio")
                        .WithMany()
                        .HasForeignKey("VestigioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnviadoPor");

                    b.Navigation("Vestigio");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Armazenamento", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "RecebidoPor")
                        .WithMany()
                        .HasForeignKey("RecebidoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Vestigio", "Vestigio")
                        .WithMany()
                        .HasForeignKey("VestigioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecebidoPor");

                    b.Navigation("Vestigio");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Credencial", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "Emissor")
                        .WithMany()
                        .HasForeignKey("EmissorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustodyChain.Web.Models.Entities.Processo", "Processo")
                        .WithMany()
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "Titular")
                        .WithMany()
                        .HasForeignKey("TitularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustodyChain.Web.Models.Entities.Vestigio", "Vestigio")
                        .WithMany()
                        .HasForeignKey("VestigioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Emissor");

                    b.Navigation("Processo");

                    b.Navigation("Titular");

                    b.Navigation("Vestigio");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Descarte", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "AprovadoPor")
                        .WithMany()
                        .HasForeignKey("AprovadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Anexo", "AutorizacaoAnexo")
                        .WithMany()
                        .HasForeignKey("AutorizacaoAnexoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "SolicitadoPor")
                        .WithMany()
                        .HasForeignKey("SolicitadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Vestigio", "Vestigio")
                        .WithMany()
                        .HasForeignKey("VestigioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AprovadoPor");

                    b.Navigation("AutorizacaoAnexo");

                    b.Navigation("SolicitadoPor");

                    b.Navigation("Vestigio");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Interveniente", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Perfil", "Perfil")
                        .WithMany("Intervenientes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Lacre", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "AplicadoPor")
                        .WithMany()
                        .HasForeignKey("AplicadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Anexo", "FotoAnexo")
                        .WithMany()
                        .HasForeignKey("FotoAnexoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Lacre", "LacreAnterior")
                        .WithMany()
                        .HasForeignKey("LacreAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "RompidoPor")
                        .WithMany()
                        .HasForeignKey("RompidoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Vestigio", "Vestigio")
                        .WithMany()
                        .HasForeignKey("VestigioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AplicadoPor");

                    b.Navigation("FotoAnexo");

                    b.Navigation("LacreAnterior");

                    b.Navigation("RompidoPor");

                    b.Navigation("Vestigio");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Laudo", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Anexo", "AnexoPdf")
                        .WithMany()
                        .HasForeignKey("AnexoPdfId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "AssinadoPor")
                        .WithMany()
                        .HasForeignKey("AssinadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Laudo", "LaudoAnterior")
                        .WithMany()
                        .HasForeignKey("LaudoAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Pericia", "Pericia")
                        .WithMany("Laudos")
                        .HasForeignKey("PericiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnexoPdf");

                    b.Navigation("AssinadoPor");

                    b.Navigation("LaudoAnterior");

                    b.Navigation("Pericia");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.LogAuditoria", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "Interveniente")
                        .WithMany()
                        .HasForeignKey("IntervenienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Interveniente");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Movimentacao", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "AprovadoPor")
                        .WithMany()
                        .HasForeignKey("AprovadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "Origem")
                        .WithMany()
                        .HasForeignKey("OrigemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Vestigio", "Vestigio")
                        .WithMany()
                        .HasForeignKey("VestigioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AprovadoPor");

                    b.Navigation("CriadoPor");

                    b.Navigation("Destino");

                    b.Navigation("Origem");

                    b.Navigation("Vestigio");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.OperacaoAmostra", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "ExecutadoPor")
                        .WithMany()
                        .HasForeignKey("ExecutadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Pericia", "Pericia")
                        .WithMany("OperacoesAmostra")
                        .HasForeignKey("PericiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustodyChain.Web.Models.Entities.Vestigio", "VestigioOrigem")
                        .WithMany()
                        .HasForeignKey("VestigioOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustodyChain.Web.Models.Entities.Vestigio", "VestigioResultante")
                        .WithMany()
                        .HasForeignKey("VestigioResultanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExecutadoPor");

                    b.Navigation("Pericia");

                    b.Navigation("VestigioOrigem");

                    b.Navigation("VestigioResultante");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Pericia", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Credencial", "Credencial")
                        .WithMany()
                        .HasForeignKey("CredencialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "Perito")
                        .WithMany()
                        .HasForeignKey("PeritoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Processo", "Processo")
                        .WithMany()
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustodyChain.Web.Models.Entities.Vestigio", "Vestigio")
                        .WithMany()
                        .HasForeignKey("VestigioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Credencial");

                    b.Navigation("Perito");

                    b.Navigation("Processo");

                    b.Navigation("Vestigio");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.RegistroLedger", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Vestigio", "Vestigio")
                        .WithMany()
                        .HasForeignKey("VestigioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Vestigio");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Vestigio", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "CustodianteAtual")
                        .WithMany()
                        .HasForeignKey("CustodianteAtualId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Processo", "Processo")
                        .WithMany("Vestigios")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustodyChain.Web.Models.Entities.TipoVestigio", "TipoVestigio")
                        .WithMany("Vestigios")
                        .HasForeignKey("TipoVestigioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Criador");

                    b.Navigation("CustodianteAtual");

                    b.Navigation("Processo");

                    b.Navigation("TipoVestigio");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Perfil", b =>
                {
                    b.Navigation("Intervenientes");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Pericia", b =>
                {
                    b.Navigation("Laudos");

                    b.Navigation("OperacoesAmostra");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Processo", b =>
                {
                    b.Navigation("Vestigios");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.TipoVestigio", b =>
                {
                    b.Navigation("Vestigios");
                });
#pragma warning restore 612, 618
        }
    }
}
