// <auto-generated />
using System;
using CustodyChain.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustodyChain.Web.Migrations
{
    [DbContext(typeof(CustodyChainDbContext))]
    [Migration("20260923071551_InicialSubconjuntoMinimo")]
    partial class InicialSubconjuntoMinimo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Interveniente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AtivadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Did")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DidEmissor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Lotacao")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Matricula")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Orgao")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<byte>("PerfilId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Did")
                        .IsUnique();

                    b.HasIndex("PerfilId");

                    b.ToTable("INTERVENIENTE", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Perfil", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MetodoDid")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("PERFIL", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Processo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("DataAbertura")
                        .HasColumnType("date");

                    b.Property<string>("NomeOperacao")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("OrgaoOrigem")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("PROCESSO", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.TipoVestigio", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("AreaPericial")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("ExigeHash")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("TIPO_VESTIGIO", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Vestigio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CriadorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustodianteAtualId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataHoraColeta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescricaoIntercorrencia")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<byte>("EtapaAtual")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("FaseAtual")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool?>("HouveIntercorrencia")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LocalColeta")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MetodoColeta")
                        .HasColumnType("text");

                    b.Property<string>("NumeroEvidencia")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<long>("ProcessoId")
                        .HasColumnType("bigint");

                    b.Property<string>("RotuloConjunto")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("RotuloEvidencia")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<short>("TipoVestigioId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.HasIndex("CustodianteAtualId");

                    b.HasIndex("ProcessoId");

                    b.HasIndex("RotuloConjunto");

                    b.HasIndex("RotuloEvidencia")
                        .IsUnique();

                    b.HasIndex("TipoVestigioId");

                    b.ToTable("VESTIGIO", (string)null);
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Interveniente", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Perfil", "Perfil")
                        .WithMany("Intervenientes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Vestigio", b =>
                {
                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Interveniente", "CustodianteAtual")
                        .WithMany()
                        .HasForeignKey("CustodianteAtualId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustodyChain.Web.Models.Entities.Processo", "Processo")
                        .WithMany("Vestigios")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustodyChain.Web.Models.Entities.TipoVestigio", "TipoVestigio")
                        .WithMany("Vestigios")
                        .HasForeignKey("TipoVestigioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Criador");

                    b.Navigation("CustodianteAtual");

                    b.Navigation("Processo");

                    b.Navigation("TipoVestigio");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Perfil", b =>
                {
                    b.Navigation("Intervenientes");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.Processo", b =>
                {
                    b.Navigation("Vestigios");
                });

            modelBuilder.Entity("CustodyChain.Web.Models.Entities.TipoVestigio", b =>
                {
                    b.Navigation("Vestigios");
                });
#pragma warning restore 612, 618
        }
    }
}
